/* O servidor de maquinas gerou um arquivo de log CSV. 
Vamos importá-lo e analisa-lo dentro do nosso banco*/

/* Importando CSV */
CREATE TABLE MAQUINAS(
	MAQUINA VARCHAR(20),
	DIA INT,
	QTD NUMERIC(10,2)
);

COPY MAQUINAS
FROM 'C:\Curso SQL\LogMaquinas.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM MAQUINAS;

/* qual a media de cada maquina */

SELECT MAQUINA, AVG(QTD) AS MEDIA_QTD 
FROM MAQUINAS GROUP BY MAQUINA
ORDER BY 2 DESC;

/* arrendondando */
ROUND(COLUNA, 2)

SELECT MAQUINA, ROUND(AVG(QTD), 2) AS MEDIA_QTD 
FROM MAQUINAS GROUP BY MAQUINA
ORDER BY 2 DESC;


/* QUAL A MODA DAS QUANTIDADES*/
SELECT MAQUINA, QTD, COUNT(*) AS MODA
FROM MAQUINAS 
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC;

/* A MODA DAS QUANTIDADES DE CADA MAQUINA */
SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;


/* MODA DO MEU DATASET INTEIRO */
SELECT QTD, COUNT(*) AS MODA 
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;

/* qual o maximo e minimo e amplitude de cada maquina */
SELECT MAQUINA,
	MAX(QTD) AS MAXIMO,
	MIN(QTD) AS MINIMO,
	MAX(QTD) - MIN(QTD) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;

/* ACRESCENTE MEDIA AO RELATORIO */
SELECT MAQUINA,
	ROUND(AVG(QTD), 2) AS MEDIA,
	MAX(QTD) AS MAXIMO,
	MIN(QTD) AS MINIMO,
	MAX(QTD) - MIN(QTD) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;

/* DESVIO PADRAO E VARIANCIA*/
/* DESVIO PADRAO */STDDEV_POP(COLUNA)
/* VARIANCIA*/ VAR_POP(COLUNA)

SELECT MAQUINA,
	ROUND(AVG(QTD), 2) AS MEDIA,
	MAX(QTD) AS MAXIMO,
	MIN(QTD) AS MINIMO,
	MAX(QTD) - MIN(QTD) AS AMPLITUDE,
	ROUND(STDDEV_POP(QTD), 2) AS DESV_PAD,
	ROUND(VAR_POP(QTD), 2) AS VARIANCIA
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;

/* MEDIANA */

CREATE OR REPLACE FUNCTION _final_median(NUMERIC[])
   RETURNS NUMERIC AS
$$ /* mudando o delimitador */
   SELECT AVG(val)
   FROM (
     SELECT val
     FROM unnest($1) val
     ORDER BY 1
     LIMIT  2 - MOD(array_upper($1, 1), 2)
     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
   ) sub;
$$
LANGUAGE 'sql' IMMUTABLE;


										 
CREATE AGGREGATE median(NUMERIC) (
  SFUNC=array_append,
  STYPE=NUMERIC[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);

SELECT ROUND(MEDIAN(QTD), 2) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01';


INSERT INTO MAQUINAS VALUES('Maquina 01',11,15.9);
INSERT INTO MAQUINAS VALUES('Maquina 02',11,15.4);
INSERT INTO MAQUINAS VALUES('Maquina 03',11,15.7);
INSERT INTO MAQUINAS VALUES('Maquina 01',12,30);
INSERT INTO MAQUINAS VALUES('Maquina 02',12,24);
INSERT INTO MAQUINAS VALUES('Maquina 03',12,45);

delete from maquinas where dia = 11 or dia = 12;


/*
	QUANTIDADE 
	TOTAL 
	MEDIA 
	MAXIMO 
	MINIMO 
	AMPLITUDE TOTAL 
	VARIANCIA 
	DESVIO PADRAO
	MEDIANA
	COEF VARIAÇÃO
*/

SELECT MAQUINA, 
		COUNT(QTD) AS "QUANTIDADE",
		SUM(QTD) AS "TOTAL",
		ROUND(AVG(QTD), 2) AS "MEDIA",
		MAX(QTD) AS "MAXIMO",
		MIN(QTD) AS "MINIMO",
		MAX(QTD) - MIN(QTD) AS "AMPLIT. TOTAL",
		ROUND(VAR_POP(QTD), 2) AS "VARIANCIA",
		ROUND(STDDEV_POP(QTD), 2) AS "DESV. PADRAO",
		ROUND(MEDIAN(QTD), 2) AS MEDIANA,
		ROUND((STDDEV_POP(QTD) / AVG(QTD)) * 100, 2) AS "COEF VARIACAO"
		FROM MAQUINAS
		GROUP BY MAQUINA
		ORDER BY 1;
		

/* MODA => MODE() WITHIM GROUP(ORDER BY COLUNA)*/

SELECT MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA" FROM MAQUINAS;

SELECT MAQUINA, MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA" FROM MAQUINAS GROUP BY MAQUINA;
		
		
SELECT MAQUINA, 
		COUNT(QTD) AS "QUANTIDADE",
		SUM(QTD) AS "TOTAL",
		ROUND(AVG(QTD), 2) AS "MEDIA",
		MAX(QTD) AS "MAXIMO",
		MIN(QTD) AS "MINIMO",
		MAX(QTD) - MIN(QTD) AS "AMPLIT. TOTAL",
		ROUND(VAR_POP(QTD), 2) AS "VARIANCIA",
		ROUND(STDDEV_POP(QTD), 2) AS "DESV. PADRAO",
		ROUND(MEDIAN(QTD), 2) AS MEDIANA,
		ROUND((STDDEV_POP(QTD) / AVG(QTD)) * 100, 2) AS "COEF VARIACAO",
		MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA"
		FROM MAQUINAS
		GROUP BY MAQUINA
		ORDER BY 1;
	
		