/* O servidor de maquinas gerou um arquivo de log CSV. 
Vamos importá-lo e analisa-lo dentro do nosso banco*/

/* Importando CSV */
CREATE TABLE MAQUINAS(
	MAQUINA VARCHAR(20),
	DIA INT,
	QTD NUMERIC(10,2)
);

COPY MAQUINAS
FROM 'C:\Curso SQL\LogMaquinas.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM MAQUINAS;

/* qual a media de cada maquina */

SELECT MAQUINA, AVG(QTD) AS MEDIA_QTD 
FROM MAQUINAS GROUP BY MAQUINA
ORDER BY 2 DESC;

/* arrendondando */
ROUND(COLUNA, 2)

SELECT MAQUINA, ROUND(AVG(QTD), 2) AS MEDIA_QTD 
FROM MAQUINAS GROUP BY MAQUINA
ORDER BY 2 DESC;


/* QUAL A MODA DAS QUANTIDADES*/
SELECT MAQUINA, QTD, COUNT(*) AS MODA
FROM MAQUINAS 
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC;

/* A MODA DAS QUANTIDADES DE CADA MAQUINA */
SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;


/* MODA DO MEU DATASET INTEIRO */
SELECT QTD, COUNT(*) AS MODA 
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;

/* qual o maximo e minimo e amplitude de cada maquina */
SELECT MAQUINA,
	MAX(QTD) AS MAXIMO,
	MIN(QTD) AS MINIMO,
	MAX(QTD) - MIN(QTD) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;

/* ACRESCENTE MEDIA AO RELATORIO */
SELECT MAQUINA,
	ROUND(AVG(QTD), 2) AS MEDIA,
	MAX(QTD) AS MAXIMO,
	MIN(QTD) AS MINIMO,
	MAX(QTD) - MIN(QTD) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;

/* DESVIO PADRAO E VARIANCIA*/
STDDEV_POP(COLUNA)
VAR_POP(COLUNA)

SELECT MAQUINA,
	ROUND(AVG(QTD), 2) AS MEDIA,
	MAX(QTD) AS MAXIMO,
	MIN(QTD) AS MINIMO,
	MAX(QTD) - MIN(QTD) AS AMPLITUDE,
	ROUND(STDDEV_POP(QTD), 2) AS DESV_PAD,
	ROUND(VAR_POP(QTD), 2) AS VARIANCIA
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;



